### ISSUE TITLE
Scale or zoom issue

### ISSUE THREAD

**Issue by Maxcdr** [PromGames/Coursedrawer#20]
Here is what I get with Poebene map (http://www.modhoster.com/mods/poebene15):

![sans titre](https://cloud.githubusercontent.com/assets/10348839/5814831/08032f2c-a090-11e4-8734-ebb20078b503.png)

The screenshot shows CD fully zoomed out.

My Courseplay.xml file: https://gist.github.com/Maxcdr/240dc93829b3c0bbc66d

**Comment by sootysax** [comment]
i am also having scale and zoom issues..

**Comment by PromGames** [comment]
@sootysax . Is this happening to all maps or just this one?. 

@Maxcdr . I am not also able to see correctly this map. I have to investigate further why this happens to this map. In any case, please update to the most recent version of CourseDrawer. Follow instructions below.

All test we have done with x4 maps (MIG Map Celle) (4096x4096) and Standard maps Bjornholm (2048x2048) works correctly.

![samplebjornholmcd4_0_006_1](https://cloud.githubusercontent.com/assets/9979168/5826539/da6b82a8-a0f3-11e4-9f06-1b9b3d08ce1d.jpg)

This seems to work perfectly as you cans see in the picture. We can have some small deviations due to elevations of the map. (Course play is 2D coordinates) 

**We have just published** a new beta tester version. ***Course Drawer 4.0.006_1***. Download the zip file, uncompress and look for the `\publish\application_files\CourseDrawer_4_0_006_1\coursedrawer.exe.deploy`. Just delete `.deploy` from the extension. 

You will also find a folder with the maps we use for tests. You can delete the rest of the files.

If you find same problem in other maps, please report.

**Comment by Maxcdr** [comment]
I still have the issue with 4.0.006_1. Also as you can see on the screenshot the right side of the windows is a little bit truncated.

![sans titre](https://cloud.githubusercontent.com/assets/10348839/5832327/f85c82ee-a143-11e4-9dd3-1687e04f4781.png)

**Comment by PromGames** [comment]
Hi Max. 

This a converted map from FS13. Looking at the terrain in the giants editor seems to be a 4x map but a little bit strange how the terrain is configured. In any case, if we resize to 4096x4096. Then you can see perfectly the results.
 

![poebene_map_issue](https://cloud.githubusercontent.com/assets/9979168/5832840/6bad4772-a14b-11e4-83ad-509ee8a8d2ad.jpg)

I think, we can close this issue now.

**Comment by Maxcdr** [comment]
Okay. Quick question: how do you resize 4096x4096?

**Comment by PromGames** [comment]
You have this already reported in issue #4 . We normally use paint.net to convert the pda_map.
Just open the `pda_map.dds` file with this tool. Normally is 1024x1024. Resize to 4096x4096 and save it as `pda_map.bmp` format.

You can get this tool at:
   http://www.getpaint.net/

We are working on the new version of courseplay_Path_Editor where the user will not need to do this process in the future, but is not available yet.
